### PR TITLE
support idea 222

### PR DESCRIPTION
**Pull request by anjia0532**

### CODE REVIEW

**Comment by anjia0532** [comment]
fixed https://github.com/nocalhost/nocalhost-intellij-plugin/issues/179
fixed https://github.com/nocalhost/nocalhost/issues/1367
fixed https://github.com/nocalhost/nocalhost/issues/1372

**Comment by chengleqi** [comment]
I use @anjia0532 complied version these days. It run correctly.
@anurnomeru

**Comment by halfcrazy** [comment]
Any updates?

**Comment by anjia0532** [comment]
官方没合并发布的情况下，我之前用 github actions 自己编译了一个，支持最新2022.2，有需要的可以自己下 https://github.com/anjia0532/nocalhost-intellij-plugin/actions/runs/2831564805 ，可以先用着 @halfcrazy

**Comment by iiQi** [comment]
都快一个月了，怎么都还没有合并呢

**Comment by jiuker** [comment]
why don't 合并

**Comment by jiuker** [comment]
@ovaldi 要不，发一个版本。vscode，用起来太难受了

**Comment by lukeqqin** [comment]
太拖了

**Pull request merged**
