### PR TITLE
feat: support idea 232

### PR DESCRIPTION
**Pull request by dingjiefeng**

### CODE REVIEW

**Comment by dingjiefeng** [comment]
#205

**Comment by dingjiefeng** [comment]
@anurnomeru

**Comment by tianyu-sz** [comment]
looks good

**Comment by ovaldi** [comment]
LGTM

**Review by tianyu-sz — APPROVED** [review]

**Comment by tianyu-sz** [comment]
image
Done some tests in 2023.2, looks good

**Comment by tianyu-sz** [comment]
this pr has been resolved by this one #212 .
plugin has been approved by Jetbrains market review and now is available publicly, resolve issue #205

**Pull request closed without merging**
